#!/bin/bash
# imos-aws calls aws with imos credentails.
#
# Usage:
#     imos-aws options...

source "$(dirname "${BASH_SOURCE}")"/imos-variables || exit 1

mkdir "${TMPDIR}/.aws"
sudo imos-aws-credentials > "${TMPDIR}/.aws/credentials"
sub::println '[profile imos-package]' > "${TMPDIR}/.aws/config"
HOME="${TMPDIR}" aws "$@"
