#!/bin/bash
# imos-aws calls aws with imos credentails.
#
# Usage:
#     imos-aws options...

source "$(dirname "${BASH_SOURCE}")"/imos-variables || exit 1
IMOSH_PREDICATE=1 eval "${IMOSH_INIT}"

mkdir "${TMPDIR}/.aws"
sudo imos-aws-credentials > "${TMPDIR}/.aws/credentials"
{
  sub::println '[default]'
  sub::println 'output = json'
  sub::println 'region = ap-northeast-1'
} > "${TMPDIR}/.aws/config"
HOME="${TMPDIR}" aws "$@"
