#!/bin/bash
# imos-start is a start-up script.
#
# imos-start is a script that should run just after boot programs.  This script
# requires the root privilege.
#
# Usage:
#     imos-start

source "$(dirname "${BASH_SOURCE}")"/imos-variables || exit 1
eval "${IMOSH_INIT}"

POKEMON="$(imos-pokemon --nocache)"

check() {
  if [ "$(whoami)" != 'root' ]; then
    LOG FATAL 'root privilege is required'
  fi
}

start::darwin() {
  LOG INFO "Initializing host names with ${POKEMON}..."
  scutil --set ComputerName "${POKEMON}"
  scutil --set LocalHostName "${POKEMON}"
  scutil --set HostName "${POKEMON}.local"

  LOG INFO 'Installing pictures...'
  local users=()
  func::imos_get_users users
  local user=''
  if [ "${#users[*]}" -ne 0 ]; then
    for user in "${users[@]}"; do
      if [ ! -L "${IMOS_ROOT}/Users/${user}/Pictures" ]; then
        LOG INFO "Replacing ${user}'s Pictures directory..."
        rm -R -f "${IMOS_ROOT}/Users/${user}/Pictures"
        ln -s "${IMOS_ROOT}/storage/home/${user}/Pictures" \
              "${IMOS_ROOT}/Users/${user}/Pictures"
      fi
    done
  fi
}

start::linux() {
  # There is nothing to do for linux.
  :
}

main() {
  check
  "start::$(sub::strtolower "${UNAME}")"
}

if [ "${#}" -eq 0 ]; then
  main
else
  LOG FATAL "imos-start requires no arguments."
fi
