#!/bin/bash
# imos-aws-credentials shows AWS credentials.
#
# Usage:
#     imos-aws-credentials

source "$(dirname "${BASH_SOURCE}")"/imos-variables || exit 1
eval "${IMOSH_INIT}"

imos-crypt --decrypt --installed_password \
    "${IMOS_BIN}/data/aws.aes256" "${TMPDIR}/credentials"
cat "${TMPDIR}/credentials"
