#!/bin/bash

set -e -u

update_profile() {
  grep -v 'usr/imos/bin' '/etc/profile' > '/tmp/profile'
  echo 'if [[ ! "${PATH}" =~ (:|^)'\''/usr/imos/bin'\''(:|$) ]]; then export PATH="/usr/imos/bin:${PATH}"; fi' >> '/tmp/profile'
  cat '/tmp/profile' > '/etc/profile'
}

setup_for_mac() {
  echo '/usr/imos/bin' > '/etc/paths.d/imos-bin'
  update_profile
}

setup_for_linux() {
  update_profile
}

if [ "$(whoami)" != 'root' ]; then
  echo 'root privilege is required.'
  exit 1
fi

OS="$(uname -s)"
case "${OS}" in
  Darwin)
    setup_for_mac
    ;;
  Linux)
    if ! type git >/dev/null 2>/dev/null; then
      if type apt-get >/dev/null 2>/dev/null; then
        apt-get -y install git
      elif type yum >/dev/null 2>/dev/null; then
        yum -y install git
      else
        echo 'git command is not found.'
      fi
    fi
    setup_for_linux
    ;;
  *)
    echo "Unsupported system: ${OS}" >&2
    exit 1
    ;;
esac

if [ -d '/usr/imos/bin' ]; then
  rm -r '/usr/imos/bin'
fi
mkdir -p '/usr/imos/bin'
git clone --depth 1 'https://github.com/imos/bin' '/usr/imos/bin'

