#!/bin/bash

set -e -u

update_profile() {
  grep -v 'usr/imos/bin' '/etc/profile' > '/tmp/profile'
  echo 'if [[ ! "${PATH}" =~ (:|^)'\''/usr/imos/bin'\''(:|$) ]]; then export PATH="/usr/imos/bin:${PATH}"; fi' >> '/tmp/profile'
  cat '/tmp/profile' > '/etc/profile'
}

setup_for_mac() {
  echo '/usr/imos/bin' > '/etc/paths.d/imos-bin'
  update_profile
}

setup_for_linux() {
  update_profile
}

if [ "$(whoami)" != 'root' ]; then
  echo 'root privilege is required.'
  exit 1
fi

if [ -d '/usr/imos/bin' ]; then
  rm -r '/usr/imos/bin'
fi
mkdir -p '/usr/imos/bin'
git clone --depth 1 'https://github.com/imos/bin' '/usr/imos/bin'

OS="$(uname -s)"
case "${OS}" in
  Darwin) setup_for_mac;;
  Linux)  setup_for_linux;;
  *)      echo "Unsupported system: ${OS}" >&2; exit 1;;
esac
