#!/bin/bash
# Update scripts inside the bin directory.
#
# This script should not use imosh so that we can revert imosh even if imosh is
# buggy.

GIT_URL='https://raw.githubusercontent.com'
TARGETS=(
  "imosh@${GIT_URL}/imos/imosh/master/imosh"
  "library/git-prompt.sh@${GIT_URL}/git/git/master/contrib/completion/git-prompt.sh"
)

cd "$(dirname "${BASH_SOURCE}")/.."

update() {
  if [ "$#" -eq 2 ]; then
    local command="$1"
    local url="$2"
    curl "${url}" > "${command}"
    chmod +x "${command}"
  else
    echo 'update requires at least two arguments.' >&2
    exit 1
  fi
}

main() {
  local target=''
  for target in "${TARGETS[@]}"; do
    IFS='@' eval "local args=(\${target})"
    if [ "${#}" -eq 1 ]; then
      if [ "${1}" != "${args[0]}" ]; then
        continue
      fi
    fi
    update "${args[@]}"
  done
}

main "${@}"
