#!/bin/bash
# Update README.md.

source "$(dirname "${BASH_SOURCE}")/../imosh" || exit 1

DEFINE_string output "$(dirname "${BASH_SOURCE}")/../README.md" \
    'README file to output.'

eval "${IMOSH_INIT}"


init_readme() {
  cat << 'EOM'
# imos-bin
bin directory used by imos.

## How to Install
Install this repository to /usr/imos/bin and configure ${PATH}:
```sh
curl https://raw.githubusercontent.com/imos/bin/master/tool/setup | sudo bash
```

## Commands
EOM
}

add_readme() {
  local file="${1}"

  echo "### ${file}"
  if grep '^eval "\${IMOSH_INIT}"$' "${file}" >/dev/null; then
    "./${file}" --help_format=markdown 2>&1 | while IFS= read -r line; do
      case "${line}" in
        '#'*) echo "###${line}";;
        *)    echo "${line}";;
      esac
    done
  else
    __imosh::show_usage \
        --format=markdown --notitle --markdown_heading='##' "${file}"
  fi
  echo
}

main() {
  local target=''
  init_readme
  for target in *; do
    if [ -x "${target}" -a ! -d "${target}" ]; then
      add_readme "${target}"
    fi
  done
}

main > "${FLAGS_output}"
