#!/bin/bash
# Update README.md.

source "$(dirname "${BASH_SOURCE}")/../imosh" || exit 1

DEFINE_string output "$(dirname "${BASH_SOURCE}")/../README.md" \
    'README file to output.'

eval "${IMOSH_INIT}"


init_readme() {
  cat << 'EOM'
# imos-bin
bin directory used by imos.

This repository is tested on drone.io (https://drone.io/github.com/imos/bin).

## How to Install/Update
Install this repository to /usr/imos/bin and configure ${PATH}:
```sh
curl https://raw.githubusercontent.com/imos/bin/master/tool/setup | sudo bash
```

Note that you can run the command multiple times safely.

## Commands
EOM
}

add_readme() {
  local file="${1}"

  echo
  echo '-----'
  echo
  echo "### ${file}"
  if grep '^eval "\${IMOSH_INIT}"$' "${file}" >/dev/null; then
    "./${file}" --help_format=markdown 2>&1 | while IFS= read -r line; do
      case "${line}" in
        '#'*) echo "###${line}";;
        *)    echo "${line}";;
      esac
    done
  else
    __imosh::show_usage \
        --format=markdown --notitle --markdown_heading='##' "${file}"
  fi
  echo
}

main() {
  local targets=()
  local target=''
  init_readme
  for target in *; do
    if [ -x "${target}" -a ! -d "${target}" ]; then
      targets+=("${target}")
    fi
  done
  local readme_all=''
  for target in "${targets[@]}"; do
    local readme="$(add_readme "${target}")"
    local lines=()
    func::trim readme
    func::explode lines $'\n' "${readme}"
    if [ "${#lines[*]}" -gt 1 ]; then
      echo "* [${target}](#${target}) ... ${lines[1]}"
    fi
    readme_all+="${readme}"$'\n\n'
  done
  echo
  echo "${readme_all}"
}

main > "${FLAGS_output}"
