#!/bin/bash
# Update scripts inside the bin directory.

# This script should not use imosh so that we can revert imosh even if imosh is
# buggy.

IMOS_GIT='https://github.com/imos'
IMOS_GIST='https://gist.githubusercontent.com/imos'
TARGETS=(
  "imosh@${IMOS_GIT}/imosh/master/imosh"
  "imofs@${IMOS_GIST}/b5a05461dfbe21ff71b9/raw/imofs"
)

cd "$(dirname "${BASH_SOURCE}")/.."

update() {
  if [ "$#" -eq 2 ]; then
    local command="$1"
    local url="$2"
    curl "${url}" > "${command}"
    chmod +x "${command}"
  else
    echo 'update requires at least two arguments.' >&2
    exit 1
  fi
}

for target in "${TARGETS[@]}"; do
  IFS='@' eval "args=(\${target})"
  update "${args[@]}"
done
